version: "3"
services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
      - ./psql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  server:
    image: golang:1.22-bookworm
    working_dir: /app
    command: go run github.com/cosmtrek/air
    volumes:
      - source: ./

        target: /app
        type: bind
    ports:
      - "8080:8080"
    environment:
      PSQL_HOST: postgres
      PSQL_PORT: 5432
      PSQL_DATABASE: y
      PSQL_USER: postgres
      PSQL_PASSWORD: postgres
      PSQL_SSLMODE: disable
    depends_on:
      - postgres

networks:
  default: {}
