import type { Metadata } from "next";
import "./globals.css";
import { Nunito, Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import { Header } from "./header/header";
import { StyledEngineProvider } from "@mui/material/styles";

const NunitoFont = Nunito({
  subsets: ["latin"],
  variable: "--font-Nunito",
});
const NotoFont = Noto_Sans_JP({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-Noto",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${NunitoFont.variable} ${NotoFont.variable}`}>
        <StyledEngineProvider injectFirst>
          <div>
            <Header />
            {children}
          </div>
        </StyledEngineProvider>
      </body>
    </html>
  );
}
